server:
    port: 8080

srping:
    datasource:
        name: springboot-mybatis
        database: MYSQL
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot
        username: root
        password: root

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: tk.mapper.model