/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class local_zcw_demo_MyNative */

#ifndef _Included_local_zcw_demo_MyNative
#define _Included_local_zcw_demo_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     local_zcw_demo_MyNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_local_zcw_demo_MyNative_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
